# @package _global_
path:
  experiments_path: ./experiments/experiments_db/
  logging_path: ./experiments/
  checkpoint_path: null
  model_path: mistralai/Mistral-7B-Instruct-v0.1
  model_name: mistral-instruct