# @package _global_
path:
  experiments_path: ./experiments/experiments_db/
  logging_path: ./experiments/
  checkpoint_path: null
  model_path: meta-llama/Llama-3.1-8B-Instruct
  model_name: llama3.1